/**
 * OpenAPI Translator
 * This is a sample translator server. For this sample, you can use the api key `special-key` to test the authorization filters. You can hire a translator and also get translations in your language (dummy :) ).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A translator for hire
*/
export class Translator {
    'id'?: number;
    'name': string;
    'lang': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lang",
            "baseName": "lang",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Translator.attributeTypeMap;
    }

    public constructor() {
    }
}

